guiSettings:
  invisible-model-data: 10367
  # GUI Titles
  salvage-gui-title: "Â§fîƒ±îƒ±î“îƒº"
  comp-gui-title: "Â§fîƒ±îƒ±î“îƒ»"
  trait-gui-title: "Â§fîƒ±îƒ±î“îƒ¼"
  trait-up-gui-title: "Â§fîƒ±îƒ±î“îƒ½"
  rank-gui-title: "Â§fîƒ±îƒ±î“îƒ¾"
  sell-gui-title: "Â§fîƒ±îƒ±î“ğœº¯"
  confirm-gui-title: "Â§fîƒ±îƒ±î“îƒ¿"
  collection-title: "Â§fîƒ±îƒ±î“î„‚"
  collection-next-title: "Â§fîƒ±îƒ±î“î„ƒ"
  collection-prev-title: "Â§fîƒ±îƒ±î“î„"
  crafting-station-title: "Â§fîƒ±îƒ±î“î„„"
  talent-tree-title: "Â§fîƒ±îƒ±î“î„†"
  # ARCHAEOLOGY EXCLUSIVES
  artefact-interact-title: "Â§fîƒ±îƒ±î“î„…"
  artefact-restore-gui-title: "Â§fîƒ±îƒ±î“î„€"